<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Validator\UniqueUserValidator' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
include_once \dirname(__DIR__, 4).'/src/Validator/UniqueUserValidator.php';

return $this->privates['App\\Validator\\UniqueUserValidator'] = new \App\Validator\UniqueUserValidator(($this->privates['App\\Repository\\UserRepository'] ?? $this->load('getUserRepositoryService.php')));
